title: "3DV"
tagline: "International Conference on 3D Vision"

url: https://3dvconf.github.io
# url: "http://www.3dv.org"
# url: "localhost:1200"
baseurl: ""

twitter: https://twitter.com/3DVconf
xiaohongshu: https://www.xiaohongshu.com/user/profile/6360cac9000000001f018c8c

permalink: /:categories/:title/
safe: false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

kramdown:
    smart_quotes:  ["apos", "apos", "ldquo", "rdquo"]

encoding: utf-8

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

whitelist:
    - jekyll-redirect-from

# Use this for production
sass:
    style: compressed
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json, assets/]


collections:
  papers:
    output: true
    permalink: /:collection/:name

    
future: true
